# Generated by Django 6.0.2 on 2026-02-26 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matchday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('date', models.DateField()),
                ('is_closed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('points_win', models.IntegerField(default=2)),
                ('points_draw', models.IntegerField(default=1)),
                ('points_loss', models.IntegerField(default=0)),
                ('bonus_undefeated', models.IntegerField(default=1)),
                ('top_matchdays_limit', models.IntegerField(default=8)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('A_WIN', 'Jugador A gana'), ('DRAW', 'Empate'), ('B_WIN', 'Jugador B gana')], max_length=10)),
                ('matchday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='league.matchday')),
                ('player_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_a', to='league.player')),
                ('player_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_b', to='league.player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='league.season'),
        ),
        migrations.AddField(
            model_name='matchday',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchdays', to='league.season'),
        ),
        migrations.CreateModel(
            name='MatchdayScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('points_base', models.IntegerField(default=0)),
                ('bonus', models.IntegerField(default=0)),
                ('total_points', models.IntegerField(default=0)),
                ('matchday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.matchday')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.season')),
            ],
            options={
                'unique_together': {('matchday', 'player')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='matchday',
            unique_together={('season', 'number')},
        ),
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.season')),
            ],
            options={
                'ordering': ['-total_points'],
                'unique_together': {('season', 'player')},
            },
        ),
    ]
