# Generated by Django 6.0.2 on 2026-04-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_matchday_score_multiplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sponsors/'),
        ),
    ]
